### ISSUE TITLE
sersic fit

### ISSUE THREAD

**Issue by leoniechevalier** [caseresearch/code-review#3]
A couple of problems on how to use python to fit a sersic profile.  the code works on synthetic data but produces odd results for my dataset.

[Archive.zip](https://github.com/caseresearch/code-review/files/946115/Archive.zip)

**Comment by manodeep** [comment]
Can you give a little more details about the exact problem you are having? Or better yet a plot or two to demonstrate what's going wrong. 

For instance, are you facing a python runtime error, or the returned fits are vastly wrong etc..

**Comment by leoniechevalier** [comment]
As it turned out my fitting issue were largely related to my dataset (now hopefully fixed).
I attached the slightly changed notebook and data. It now returns more believable values.
[Archive.zip](https://github.com/caseresearch/code-review/files/995100/Archive.zip)

**Comment by manodeep** [comment]
Fantastic. Do you want to tell us how you figured out the issue during code review?

**Comment by leoniechevalier** [comment]
distance bins (arcmin) :  [ 0.25        0.55        0.775       1.          1.23333333]
density:[ 40.10704566  20.61779945  22.40304184  11.93662073   7.09745016]

**Comment by manodeep** [comment]
What does the MLE say: https://www.johndcook.com/blog/2015/11/24/estimating-the-exponent-of-discrete-power-law-data/

**Comment by leoniechevalier** [comment]
The offset that was still present was due to a missing normalisation factor. The code was outputting the average surface density at the effective radius and not the surface density at the effective radius. The code now produces very good fits
![surface_density_revised](https://cloud.githubusercontent.com/assets/27845402/26295845/5e171e4e-3f0f-11e7-8fa3-a632ecea85c2.png)
